### ISSUE TITLE
Clustering error

### ISSUE THREAD

**Issue by choosehappy** [sidhomj/DeepTCR#20]
Getting an error when using our data, after loading with:

```
DTCRU.Load_Data(beta_sequences=beta,v_beta=v_beta,j_beta=j_beta,class_labels=class_labels,
                sample_labels=sample_labels, counts=counts)
```

Training appears to have gone ok :
```
DTCRU.Train_VAE(Load_Prev_Data=False,accuracy_min=0.85)
```
![image](https://user-images.githubusercontent.com/9681868/68883656-c5a53b00-0711-11ea-84b5-49b9f40abcef.png)

But clustering appears to fail:
![image](https://user-images.githubusercontent.com/9681868/68883628-b7571f00-0711-11ea-9c7c-31d44c234b9f.png)

same error when using phenograph method, so isn't clustering approach specific. Also happens when randomly sampling:

![image](https://user-images.githubusercontent.com/9681868/68883881-351b2a80-0712-11ea-95fd-d9d3199b7a20.png)

Is it possible that there are some outliers produced by the clustering methods, causing "sel" to be not an integer? or perhaps there is some meta data i need to set? 

Other functions appear to work okay:

![image](https://user-images.githubusercontent.com/9681868/68884031-87f4e200-0712-11ea-8fe7-b2ffb28a3d29.png)

i see #1 which has a similar error, but my data exists as a single csv file which i'm loading via pandas and chopping the necessary columns out of. as such, loading via directory doesn't appear to be an option

any ideas?

**Comment by sidhomj** [comment]
will try to look at this tonight. I don't think I've fully tested some of the unsupervised methods with data loaded through the Load_Data function. Will hopefully have a fix soon.

**Comment by choosehappy** [comment]
great, thanks! happy to help debug if useful

**Comment by sidhomj** [comment]
thanks, I definitely appreciate the help especially since the repository is under active development still and likely still has bugs that need ironing out.

**Comment by choosehappy** [comment]
not a problem, i certainly know how it is : )

**Comment by sidhomj** [comment]
I just pushed up a fix I think. Let me know if it works on your data!

**Comment by choosehappy** [comment]
Unforunately it didn't appear to fix it, same error

is there perhaps some other debugging information I can provide?

![image](https://user-images.githubusercontent.com/9681868/68934456-02674580-0797-11ea-9cb4-2c50bdce62ae.png)

**Comment by sidhomj** [comment]
I would check to make sure that your sample labels and class labels are string types and not integers or floats.

**Comment by choosehappy** [comment]
hmmm...they look good to me, appear to be all strings:

![image](https://user-images.githubusercontent.com/9681868/68945485-cc36bf80-07b0-11ea-9778-cb7b4faabe76.png)

**Comment by sidhomj** [comment]
can you send me a sampling of this csv file you're trying to run to see if I can replicate the error? jsidhom1@jhmi.edu

**Comment by choosehappy** [comment]
1 step ahead of you : ) already getting in contact with the data-owner to ensure no confidentiality issues. i suspect we'll be ok. will send afterward, likely in the next few hours

**Comment by choosehappy** [comment]
all good. just sent it

**Comment by sidhomj** [comment]
figured it out. the problem is you're passing lists to the Load_Data where in the docs, it says you need to pass numpy arrays

**Comment by choosehappy** [comment]
yes! that totally did it, thanks

i had tried to mirror the "1-loading data" tutorial, but realize now when
looking at the data quickly, a numpy lists and python lists appear similar
at fast glance. my mistake, sorry about that

you may want to add in a note in that particular file, and some type
checking in the loading function to help others

in particular, its quite unexpected that the first 2 functions work okay
(loading + training), which i perceived as the "important" functions,  but
the 3rd one (clustering) doesn't, i think thats what threw me off. i would
say more commonly if the data isn't in the right type of format the first
or second command immediately fail with a more obvious error message

anyway, very minor comments, thanks for all your help!

**Comment by sidhomj** [comment]
for sure! I added some data type checking into the Load_Data function to make sure inputs are numpy arrays, thanks!

**Comment by choosehappy** [comment]
beautiful, and thanks again for the help!
